<template>
  <div v-if="image" class="image-details">
    <img :src="image.url" :alt="image.prompt" class="w-full max-w-3xl mx-auto rounded-lg shadow-lg" />
    <div class="mt-8 max-w-3xl mx-auto">
      <h1 class="text-3xl font-bold mb-4">{{ image.prompt }}</h1>
      <div class="mb-4">
        <p><strong>Generated by:</strong> {{ image.generator }}</p>
        <p><strong>Author:</strong> {{ image.author }}</p>
        <p><strong>Created at:</strong> {{ formatDate(image.createdAt) }}</p>
      </div>
      <div class="mb-4">
        <h2 class="text-2xl font-semibold mb-2">Tags</h2>
        <div class="flex flex-wrap gap-2">
          <span
            v-for="tag in image.tags"
            :key="tag"
            class="px-3 py-1 bg-blue-100 text-blue-800 rounded-full"
          >
            {{ tag }}
          </span>
        </div>
      </div>
      <div class="mb-8">
        <h2 class="text-2xl font-semibold mb-2">Source</h2>
        <a :href="image.sourceUrl" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:underline">
          View original post
        </a>
      </div>
      <AuthorComment :comment="authorComment" />
      <RelatedImages :images="relatedImages" />
    </div>
  </div>
  <div v-else-if="loading" class="text-center">
    <p class="text-xl">Loading image details...</p>
  </div>
  <div v-else class="text-center text-red-500">
    <p>Failed to load image details.</p>
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { storeToRefs } from 'pinia'
import { useImageStore } from '@/store/images'
import AuthorComment from '@/components/AuthorComment.vue'
import RelatedImages from '@/components/RelatedImages.vue'
import { Comment } from '@/types'

export default defineComponent({
  name: 'ImageDetails',
  components: {
    AuthorComment,
    RelatedImages,
  },
  setup() {
    const route = useRoute()
    const imageStore = useImageStore()
    const { currentImage: image, loading, error } = storeToRefs(imageStore)
    const authorComment = ref<Comment | null>(null)
    const relatedImages = ref([])

    onMounted(async () => {
      const imageId = route.params.id as string
      await imageStore.fetchImageById(imageId)
      // Fetch author comment and related images here
    })

    const formatDate = (date: Date) => {
      return new Date(date).toLocaleDateString()
    }

    return {
      image,
      loading,
      error,
      authorComment,
      relatedImages,
      formatDate,
    }
  },
})
</script>