<template>
  <div class="image-card bg-white rounded-lg shadow-md overflow-hidden">
    <img :src="image.url" :alt="image.prompt" class="w-full h-48 object-cover" />
    <div class="p-4">
      <h3 class="text-lg font-semibold truncate">{{ image.prompt }}</h3>
      <p class="text-sm text-gray-600">Generated by: {{ image.generator }}</p>
      <p class="text-sm text-gray-600">Author: {{ image.author }}</p>
      <div class="mt-2 flex flex-wrap gap-1">
        <span
          v-for="tag in image.tags.slice(0, 3)"
          :key="tag"
          class="px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full"
        >
          {{ tag }}
        </span>
        <span v-if="image.tags.length > 3" class="px-2 py-1 bg-gray-100 text-gray-800 text-xs rounded-full">
          +{{ image.tags.length - 3 }} more
        </span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue'
import { Image } from '@/types'

export default defineComponent({
  name: 'ImageCard',
  props: {
    image: {
      type: Object as PropType<Image>,
      required: true,
    },
  },
})
</script>